server:
  # 服务端口
  port: 8089
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
spring:
  profiles:
    # 环境切换：dev-开发环境，prod-生产环境
    active: dev
  jackson:    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8 
  servlet: 
    multipart: 
      max-file-size: 3MB
      max-request-size: 5MB
  aop:
    proxy-target-class: true
    auto: true
  

# 分页插件     
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  
# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: false
  # 排除链接（多个用逗号分隔）
  excludes: /ui/*
  # 匹配链接
  urlPatterns: /user/*,/role/*,/menu/*,/dept/*
      
logging:
  level:
     com.frank: debug  file:    path: /log
    name: frank-boot.log
